package com.gulfappdeveloper.projectreport.presentation.screens.purchase_screens.screens.purchase_summary_screens.query_screen.util

import com.gulfappdeveloper.projectreport.presentation.screen_util.UiEvent

data class QueryPurchaseSummaryReportScreenUiEvent(val uiEvent: UiEvent)
